---
stages:
  - build
  - tar
  - publish_32
  - publish_64
  - publish_xrd
#  - non-free

include:
  - CI/Alma10-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Alma10-gcc-cmake-gen-64bit.yml
  - CI/Alma10-gcc-cmake-gen-aarch64-xrootd.yml
  - CI/Alma10-gcc-cmake-gen-aarch64.yml
  - CI/Alma8-gcc-cmake-gen-32bit.yml
  - CI/Alma8-gcc-cmake-gen-64bit.yml
  - CI/Alma8-gcc-cmake-gen-aarch64.yml
  - CI/Alma9-gcc-cmake-gen-32bit.yml
  - CI/Alma9-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Alma9-gcc-cmake-gen-64bit.yml
  - CI/Alma9-gcc-cmake-gen-aarch64-xrootd.yml
  - CI/Alma9-gcc-cmake-gen-aarch64.yml
  - CI/Centos7-gcc-cmake-gen-32bit.yml
  - CI/Centos7-gcc-cmake-gen-64bit.yml
  - CI/Centos7-gcc-imake-gen-32bit.yml
  - CI/Centos7-gcc-imake-gen-64bit.yml
  - CI/Centos8-nvc-cmake-gen-64bit.yml
  - CI/Centos9-gcc-cmake-gen-32bit.yml
  - CI/Centos9-gcc-imake-gen-32bit.yml
  - CI/Centos9-gcc-imake-gen-64bit.yml
  - CI/Debian12-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Debian12-gcc-cmake-gen-64bit.yml
  - CI/Debian12-gcc-cmake-gen-aarch64-xrootd.yml
  - CI/Debian13-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Debian13-gcc-cmake-gen-64bit.yml
  - CI/Fedora42-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Fedora42-gcc-cmake-gen-64bit.yml
  - CI/Fedora42-gcc-cmake-rpm-64bit.yml
  - CI/Fedora42-gcc-imake-gen-64bit-xrootd.yml
  - CI/Fedora42-gcc-imake-gen-64bit.yml
  - CI/Fedora43-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Fedora43-gcc-cmake-gen-64bit.yml
  - CI/Fedora44-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Fedora44-gcc-cmake-gen-64bit.yml
  - CI/SL4-g77-cmake-gen-32bit.yml
  - CI/SL4-g77-cmake-gen-64bit.yml
  - CI/SL4-g77-cmake-rpm-64bit.yml
  - CI/SL4-gcc-cmake-gen-32bit.yml
  - CI/SL4-gcc-cmake-gen-64bit.yml
  - CI/SL4-gcc-imake-gen-32bit.yml
  - CI/SL4-gcc-imake-gen-64bit.yml
  - CI/SL5-gcc-cmake-gen-32bit.yml
  - CI/SL5-gcc-cmake-gen-64bit.yml
  - CI/SL5-gcc-cmake-rpm-64bit.yml
  - CI/SL5-gcc-imake-gen-32bit.yml
  - CI/SL5-gcc-imake-gen-64bit.yml
  - CI/SL6-gcc-cmake-gen-32bit.yml
  - CI/SL6-gcc-cmake-gen-64bit.yml
  - CI/SL6-gcc-cmake-rpm-64bit.yml
  - CI/SL6-gcc-imake-gen-32bit.yml
  - CI/SL6-gcc-imake-gen-64bit.yml
  - CI/Ubuntu20-gcc-cmake-gen-64bit.yml
  - CI/Ubuntu20-gcc-imake-gen-64bit.yml
  - CI/Ubuntu22-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Ubuntu22-gcc-cmake-gen-64bit.yml
  - CI/Ubuntu22-gcc-imake-gen-64bit.yml
  - CI/Ubuntu24-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Ubuntu24-gcc-cmake-gen-64bit.yml
  - CI/Ubuntu24-gcc-imake-gen-64bit-xrootd.yml
  - CI/Ubuntu24-gcc-imake-gen-64bit.yml
  - CI/Ubuntu26-gcc-cmake-gen-64bit-xrootd.yml
  - CI/Ubuntu26-gcc-cmake-gen-64bit.yml
  - CI/publish-free.yml
#  - CI/non-free.yml
  
