#!/bin/bash
# 32bit binaries?
LEGACY=$1
#[GNU,INTEL,NVIDIA,CLANG,etc]
TOOLCHAIN=$2
# CERNLIB version
CL_VERSION=$3
# Support for xrootd
XROOTD=$4

if [ "x$LEGACY" = "x32bit" ] ; then
    echo '#define CERNLIB_32BITCROSS YES' >> config/host.def
    export ADDFOPT='-m32'
fi

if [ "x$LEGACY" = "x" ] ; then
    echo 'Please specify if you want to build in 32bit or not'
    exit 1
fi
    
if [ "x$TOOLCHAIN" = "x" ] ; then
    echo 'Please define the toolchain'
    exit 1
fi
    
if [ "x$XROOTD" = "x" ] || [ "x$XROOTD" = "xoff" ] || [ "x$XROOTD" = "xOFF" ]  ; then
    echo 'Compiling without XROOTD support'
else
    echo 'Enabling XROOTD support'
    echo '#define CERNLIB_XROOTD YES' >> config/host.def
    if [ -x "/usr/bin/xrootd-config" ]; then
	XROOTD_VERSION=`/usr/bin/xrootd-config --version|cut -d\- -f1`
    else
	if [ -x "/usr/local/bin/xrootd-config" ]; then
            XROOTD_VERSION=`/usr/local/bin/xrootd-config --version|cut -d\- -f1`
	else
	    echo "Cannot find xrootd. Exiting"
	    exit 1
	fi
    fi
    echo "Found xrootd version ${XROOTD_VERSION}"
    if [[ "x${XROOTD_VERSION}" < "x5.7.4" ]]; then
	echo "Using build-in XrdPosix headers"
        echo '#define XROOTD_BUILDIN_HEADERS YES' >> config/host.def
	export ADDCOPT='-DXROOTD_BUILDIN_HEADERS -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64'
    else
	echo "Using upsteam XrdPosix headers"
	export ADDCOPT='-D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64'
    fi
    export CERNLIB_XROOTD=ON
fi

# support for xrootd

# check for CentOS/RHEL
if [ -e  /etc/os-release ]; then
    flavor=`cat /etc/os-release | grep ^ID=| sed -e 's/\"//'g| cut -d= -f 2`
else
    # older RH versions don't have /etc/os-release yet
    if [ -e /etc/redhat-release ]; then
	flavor='rhel'
    fi
fi

if [ "x$flavor" = "xcentos" ] || [ "x$flavor" = "xrhel" ] || [  "x$flavor" = "xalmalinux" ]; then
    # there is no external libXbae available on these
    echo '#define CERNLIB_NOLIBXBAE YES' >> config/host.def
fi
if [ "$(uname)" = "Darwin" ]; then
    echo '#define CERNLIB_NOLIBXBAE YES' >> config/host.def
fi

export CVSCOSRC=`pwd`
if [ -z $CERN ]; then
 export CERN=/tmp/cern
fi
if [ "x$CL_VERSION" = "x" ]; then
    if [ "x$CERN_LEVEL" = "x" ]; then
     export CERN_LEVEL=new
    fi
else
    export CERN_LEVEL=$CL_VERSION
fi
export CERN_ROOT=${CERN}/$CERN_LEVEL
export CERN_LIB=${CERN_ROOT}/lib
export CERN_BIN=${CERN_ROOT}/bin
export CERN_INCLUDEDIR=${CERN_ROOT}/include
export CERN_INCLUDE=${CERN_ROOT}/include
export PATH=$CVSCOSRC/scripts:/usr/X11R6/bin/:$CERN_BIN:$PATH
if [ $TOOLCHAIN = GNU-* ]; then
N=$(echo $TOOLCHAIN | cut -f 2 -d\-)
echo 'FORTRAN  = gfortran-'$N' -g' >> lapack/make.inc
echo 'LOADER  = gfortran-'$N' ' >> lapack/make.inc
echo '#undef FortranCmd' >> config/host.def
echo '#define FortranCmd gfortran-'$N' -g' >> config/host.def
echo '#undef CcCmd' >> config/host.def
echo '#define CcCmd gcc-'$N' -g' >> config/host.def
echo '#define DoRanlibCmd NO' >> config/host.def
gsed -i 's/CcCmd\ cc/CcCmd\ gcc\-'$N'/g' config/MacOSX.cf
echo '#define ArCmd ArCmdBase clq' >> config/host.def
cat config/MacOSX.cf
fi
#
# first build lapack library
#
# cleanup
find lapack -name \*.o -exec rm -f \{} \;
# first build BLAS
cd $CVSCOSRC/lapack/BLAS/SRC
make || exit $?
mkdir -p $CERN_ROOT/lib
mv ../../blas_LINUX.a $CERN_ROOT/lib/libblas.a
cd $CVSCOSRC/lapack/SRC
make || exit $?
mv ../lapack_LINUX.a $CERN_ROOT/lib/liblapack.a
cd $CERN_ROOT/lib/
# create compatibility links
ln -sf liblapack.a liblapack3.a
cd $CVSCOSRC

#
# create a build directory
mkdir build
cd build
cp ../Imakefile .

#
# create Makefile
$CVSCOSRC/config/imake_boot || exit $?

#
# create the tree
make tree  || exit $?

# install the scripts
cd scripts
make install.bin  || exit $?
cd ..

#
# build kuipc
make -j 8 bin/kuipc  || exit $?

#
# build cernlib
make -j 16  || exit $?

#
# build old patchy
cd $CVSCOSRC/build/patchy4
make install.lib  || exit $?
make install.bin  || exit $?
cd ..
#$
#
# DEBUGGING
echo "Testing cernlib script"
which cernlib
cernlib kernlib
cernlib -dy kernlib
env | grep CERNLIB
echo "END of testing cernlib script"

# build new patchy
cd $CVSCOSRC/build/patchy5
make install.lib  || exit $?
make install.bin  || exit $?
cd ..

#
# build paw
cd $CVSCOSRC/build/pawlib
make install.lib  || exit $?
make install.bin  || exit $?

#
# build and install zftp
cd $CVSCOSRC/build/packlib/cspack/programs
make install.bin  || exit $?

#
# build and install packlib executables
cd $CVSCOSRC/build/packlib
make install.lib  || exit $?
make install.bin  || exit $?

# build and install graflib executables
cd $CVSCOSRC/build/graflib
make install.lib  || exit $?
make install.bin  || exit $?

cd $CVSCOSRC/build
make install.include

#
# create a local copy of xneut.dat
cd $CVSCOSRC
rm -f $CERN_LIB/xsneut95.dat
cp geant321/data/xsneut95.dat $CERN_ROOT/lib/xsneut95.dat

# final checks
rc=0
nlibs=`ls $CERN_LIB/| wc -l| tr -d ' '`
nexp=37
if [ "x$nlibs" = "x$nexp" ]; then
    echo "All expected libraries have been created"
else
    echo "FATAL: Missing or unexpected libraries"
    echo "Found $nlibs and expected $nexp"
    ls $CERN_LIB |sort
    rc=1
    exit $rc
fi
nbin=`ls $CERN_BIN/| wc -l| tr -d ' '`
nexp=45
if [ "x$nbin" = "x$nexp" ]; then
    echo "All expected binaries have been created"
else
    echo "FATAL: Missing or unexpected binaries"
    echo "Found $nbin and expected $nexp"
    ls $CERN_BIN| sort
    rc=2
    exit $rc
fi

# make tests
test_dirs='mclibs kernlib packlib phtools geant321 graflib'
if [ -e __dist_failed_builds ]; then
  rm -f __dist_failed_builds
fi
touch $CVSCOSRC/build/__dist_failed_build
set -e
for dir in $test_dirs; do
    cd $CVSCOSRC/build/$dir;
    make test > $CVSCOSRC/build/__$dir.log || (cat $CVSCOSRC/build/__$dir.log && exit 1)
    ret=$?
    if [ "x$ret" = "x3" ]; then
        echo $dir >> $CVSCOSRC/build/__dist_failed_builds
        echo "Tests failed for $dir with $ret"
        rc=3
    fi
done
cd $CVSCOSRC

if [ "x$rc" = "x3" ]; then
    echo "ERROR: Tests failed"
    cat $CVSCOSRC/build/__dist_failed_build
    exit $rc
else
    echo "All required tests succeeded"
fi
rm -f $CVSCOSRC/build/__dist_failed_build
# pack artifacts as tar ball
dir=`pwd`
if [ ! -d cern ]; then
    mkdir cern
fi
cd $CERN
tar -cf - ./$CERN_LEVEL | (cd $dir/cern; tar -xf -)
cd $dir
