  set(C_C_FLAGS_TO_CHECK       "-Wno-cpp"
                               "-flto=no"
                               "-O1"
                               "-g"
                               "-Wno-incompatible-pointer-types"
                               "-Wno-format"
                               "-Wno-implicit-function-declaration"
                               "-Wno-implicit-int"
                               "-Wno-return-type"
                               "-Wno-switch"
                               "-qsuppress=1500-030"
                               "-Wno-absolute-value"
                               "-Wno-constant-logical-operand"
                               )